<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

$relationships = array (
  'bhea_member_levels_modified_user' => 
  array (
    'id' => '109c4ce7-e9cd-5c83-4aeb-52afdc978777',
    'relationship_name' => 'bhea_member_levels_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_member_levels',
    'rhs_table' => 'bhea_member_levels',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'bhea_member_levels_created_by' => 
  array (
    'id' => '10cacfd6-06f8-3698-c738-52afdcbf36a9',
    'relationship_name' => 'bhea_member_levels_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_member_levels',
    'rhs_table' => 'bhea_member_levels',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'bhea_member_levels_activities' => 
  array (
    'id' => '10fadadb-fde3-2dee-15b7-52afdcdf1989',
    'relationship_name' => 'bhea_member_levels_activities',
    'lhs_module' => 'Bhea_member_levels',
    'lhs_table' => 'bhea_member_levels',
    'lhs_key' => 'id',
    'rhs_module' => 'Activities',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_member_levels',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'bhea_member_levels_assigned_user' => 
  array (
    'id' => '11bc3ccd-a0e6-5d8b-2bba-52afdc40a256',
    'relationship_name' => 'bhea_member_levels_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_member_levels',
    'rhs_table' => 'bhea_member_levels',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'bhea_member_levels_bhea_memberships_1' => 
  array (
    'id' => '292062cd-e15b-77ce-5b75-52afdcd417d9',
    'relationship_name' => 'bhea_member_levels_bhea_memberships_1',
    'lhs_module' => 'Bhea_member_levels',
    'lhs_table' => 'bhea_member_levels',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Memberships',
    'rhs_table' => 'bhea_memberships',
    'rhs_key' => 'id',
    'join_table' => 'bhea_member_levels_bhea_memberships_1_c',
    'join_key_lhs' => 'bhea_member_levels_bhea_memberships_1bhea_member_levels_ida',
    'join_key_rhs' => 'bhea_member_levels_bhea_memberships_1bhea_memberships_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_member_levels',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_member_levels_opportunities_1' => 
  array (
    'id' => '29536e7b-ca25-a93b-3e94-52afdc96df93',
    'relationship_name' => 'bhea_member_levels_opportunities_1',
    'lhs_module' => 'Bhea_member_levels',
    'lhs_table' => 'bhea_member_levels',
    'lhs_key' => 'id',
    'rhs_module' => 'Opportunities',
    'rhs_table' => 'opportunities',
    'rhs_key' => 'id',
    'join_table' => 'bhea_member_levels_opportunities_1_c',
    'join_key_lhs' => 'bhea_member_levels_opportunities_1bhea_member_levels_ida',
    'join_key_rhs' => 'bhea_member_levels_opportunities_1opportunities_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_member_levels_bhea_pricing_line_item_1' => 
  array (
    'id' => '2e6b4e30-dd48-a6d9-6a77-52afdcacf2de',
    'relationship_name' => 'bhea_member_levels_bhea_pricing_line_item_1',
    'lhs_module' => 'Bhea_member_levels',
    'lhs_table' => 'bhea_member_levels',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Pricing_Line_Item',
    'rhs_table' => 'bhea_pricing_line_item',
    'rhs_key' => 'id',
    'join_table' => 'bhea_member_levels_bhea_pricing_line_item_1_c',
    'join_key_lhs' => 'bhea_membe43fe_levels_ida',
    'join_key_rhs' => 'bhea_membe25b3ne_item_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_member_levels',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
);