<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
	'built_in_version' => '7.1.0',
    'acceptable_sugar_versions' => 
    array (
      0 => '7.1.0',
  ),
    'acceptable_sugar_flavors' => 
    array (
      0 => 'PRO',
  ),
  'readme' => '',
  'key' => 'Bhea',
  'author' => 'Bhea',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'project_Member',
  'published_date' => '2013-11-22 05:26:20',
  'type' => 'module',
  'version' => 1385097981,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'project_Member',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/Member',
      'to' => 'custom/modulebuilder/packages/Member',
    ),
  ),
);
