<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

$relationships = array (
  'bhea_sponsor_modified_user' => 
  array (
    'id' => '43988e89-1685-9d43-0512-52b19868dd2c',
    'relationship_name' => 'bhea_sponsor_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Sponsor',
    'rhs_table' => 'bhea_sponsor',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'bhea_sponsor_created_by' => 
  array (
    'id' => '43b14368-5e34-ac24-301e-52b198c5e250',
    'relationship_name' => 'bhea_sponsor_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Sponsor',
    'rhs_table' => 'bhea_sponsor',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'bhea_sponsor_activities' => 
  array (
    'id' => '43c9bd35-b1ad-ff59-c08f-52b198d82b11',
    'relationship_name' => 'bhea_sponsor_activities',
    'lhs_module' => 'Bhea_Sponsor',
    'lhs_table' => 'bhea_sponsor',
    'lhs_key' => 'id',
    'rhs_module' => 'Activities',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Sponsor',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'bhea_sponsor_assigned_user' => 
  array (
    'id' => '442fbb43-b2de-4737-b1c2-52b1980cdf6b',
    'relationship_name' => 'bhea_sponsor_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Sponsor',
    'rhs_table' => 'bhea_sponsor',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'bhea_sponsor_bhea_sessions_1' => 
  array (
    'id' => '5dc7de4b-14c0-12d9-7c89-52b1982569f4',
    'relationship_name' => 'bhea_sponsor_bhea_sessions_1',
    'lhs_module' => 'Bhea_Sponsor',
    'lhs_table' => 'bhea_sponsor',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Sessions',
    'rhs_table' => 'bhea_sessions',
    'rhs_key' => 'id',
    'join_table' => 'bhea_sponsor_bhea_sessions_1_c',
    'join_key_lhs' => 'bhea_sponsor_bhea_sessions_1bhea_sponsor_ida',
    'join_key_rhs' => 'bhea_sponsor_bhea_sessions_1bhea_sessions_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_sponsor',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_events_bhea_sponsor_1' => 
  array (
    'id' => '5de3f550-96f0-d0e1-a9dd-52b198dfdba5',
    'relationship_name' => 'bhea_events_bhea_sponsor_1',
    'lhs_module' => 'Bhea_Events',
    'lhs_table' => 'bhea_events',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Sponsor',
    'rhs_table' => 'bhea_sponsor',
    'rhs_key' => 'id',
    'join_table' => 'bhea_events_bhea_sponsor_1_c',
    'join_key_lhs' => 'bhea_events_bhea_sponsor_1bhea_events_ida',
    'join_key_rhs' => 'bhea_events_bhea_sponsor_1bhea_sponsor_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_events',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_sponsor_bhea_sponsorship_1' => 
  array (
    'id' => '5fe658d6-b78a-0ea9-d468-52b198967510',
    'relationship_name' => 'bhea_sponsor_bhea_sponsorship_1',
    'lhs_module' => 'Bhea_Sponsor',
    'lhs_table' => 'bhea_sponsor',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Sponsorship',
    'rhs_table' => 'bhea_sponsorship',
    'rhs_key' => 'id',
    'join_table' => 'bhea_sponsor_bhea_sponsorship_1_c',
    'join_key_lhs' => 'bhea_sponsor_bhea_sponsorship_1bhea_sponsor_ida',
    'join_key_rhs' => 'bhea_sponsor_bhea_sponsorship_1bhea_sponsorship_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_sponsor',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
);