<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

$relationships = array (
  'bhea_sponsorship_types_modified_user' => 
  array (
    'id' => 'dce1f0cf-bb0d-b47b-2abf-52b3f1c2021b',
    'relationship_name' => 'bhea_sponsorship_types_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'bhea_Sponsorship_Types',
    'rhs_table' => 'bhea_sponsorship_types',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'bhea_sponsorship_types_created_by' => 
  array (
    'id' => 'dcf3c0af-7015-213a-5ff0-52b3f1cc1cd9',
    'relationship_name' => 'bhea_sponsorship_types_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'bhea_Sponsorship_Types',
    'rhs_table' => 'bhea_sponsorship_types',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'bhea_sponsorship_types_activities' => 
  array (
    'id' => 'dd06e70e-8d6d-2750-4831-52b3f1614602',
    'relationship_name' => 'bhea_sponsorship_types_activities',
    'lhs_module' => 'bhea_Sponsorship_Types',
    'lhs_table' => 'bhea_sponsorship_types',
    'lhs_key' => 'id',
    'rhs_module' => 'Activities',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'bhea_Sponsorship_Types',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'bhea_sponsorship_types_assigned_user' => 
  array (
    'id' => 'dd54da88-1527-6cfd-9760-52b3f13aa35c',
    'relationship_name' => 'bhea_sponsorship_types_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'bhea_Sponsorship_Types',
    'rhs_table' => 'bhea_sponsorship_types',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'bhea_events_bhea_sponsorship_types_1' => 
  array (
    'id' => 'e93b37c4-c021-8280-c5e4-52b3f13784ab',
    'relationship_name' => 'bhea_events_bhea_sponsorship_types_1',
    'lhs_module' => 'Bhea_Events',
    'lhs_table' => 'bhea_events',
    'lhs_key' => 'id',
    'rhs_module' => 'bhea_Sponsorship_Types',
    'rhs_table' => 'bhea_sponsorship_types',
    'rhs_key' => 'id',
    'join_table' => 'bhea_events_bhea_sponsorship_types_1_c',
    'join_key_lhs' => 'bhea_events_bhea_sponsorship_types_1bhea_events_ida',
    'join_key_rhs' => 'bhea_events_bhea_sponsorship_types_1bhea_sponsorship_types_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'ForBhea_sponsorship_types',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_sponsorship_types_opportunities_1' => 
  array (
    'id' => 'e9805616-76cd-7fa5-cedd-52b3f1968a35',
    'relationship_name' => 'bhea_sponsorship_types_opportunities_1',
    'lhs_module' => 'bhea_Sponsorship_Types',
    'lhs_table' => 'bhea_sponsorship_types',
    'lhs_key' => 'id',
    'rhs_module' => 'Opportunities',
    'rhs_table' => 'opportunities',
    'rhs_key' => 'id',
    'join_table' => 'bhea_sponsorship_types_opportunities_1_c',
    'join_key_lhs' => 'bhea_sponsorship_types_opportunities_1bhea_sponsorship_types_ida',
    'join_key_rhs' => 'bhea_sponsorship_types_opportunities_1opportunities_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_sponsorship_types',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_sessions_bhea_sponsorship_types_1' => 
  array (
    'id' => 'eb05323d-58c8-e8ec-dcab-52b3f1a0d36e',
    'relationship_name' => 'bhea_sessions_bhea_sponsorship_types_1',
    'lhs_module' => 'Bhea_Sessions',
    'lhs_table' => 'bhea_sessions',
    'lhs_key' => 'id',
    'rhs_module' => 'bhea_Sponsorship_Types',
    'rhs_table' => 'bhea_sponsorship_types',
    'rhs_key' => 'id',
    'join_table' => 'bhea_sessions_bhea_sponsorship_types_1_c',
    'join_key_lhs' => 'bhea_sessions_bhea_sponsorship_types_1bhea_sessions_ida',
    'join_key_rhs' => 'bhea_sessions_bhea_sponsorship_types_1bhea_sponsorship_types_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_sessions',
    'lhs_subpanel' => 'ForBhea_sponsorship_types',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_sponsorship_types_bhea_sponsorship_1' => 
  array (
    'id' => 'eca48b98-7a6f-8bd7-ebc4-52b3f17fe7f9',
    'relationship_name' => 'bhea_sponsorship_types_bhea_sponsorship_1',
    'lhs_module' => 'bhea_Sponsorship_Types',
    'lhs_table' => 'bhea_sponsorship_types',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Sponsorship',
    'rhs_table' => 'bhea_sponsorship',
    'rhs_key' => 'id',
    'join_table' => 'bhea_sponsorship_types_bhea_sponsorship_1_c',
    'join_key_lhs' => 'bhea_sponsd4cdp_types_ida',
    'join_key_rhs' => 'bhea_sponsorship_types_bhea_sponsorship_1bhea_sponsorship_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_sponsorship_types',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
);