<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

$relationships = array (
  'bhea_orders_modified_user' => 
  array (
    'id' => '40acc8b3-91aa-2baf-bba2-52b90726fc1b',
    'relationship_name' => 'bhea_orders_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Orders',
    'rhs_table' => 'bhea_orders',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_orders_created_by' => 
  array (
    'id' => '40c56a55-2c2c-e930-887f-52b9071b6faa',
    'relationship_name' => 'bhea_orders_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Orders',
    'rhs_table' => 'bhea_orders',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_orders_assigned_user' => 
  array (
    'id' => '41400306-a1a0-84a3-0d93-52b907e37be5',
    'relationship_name' => 'bhea_orders_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Orders',
    'rhs_table' => 'bhea_orders',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_orders_bhea_payments_1' => 
  array (
    'id' => '5e036325-dd79-a422-b76a-52b907e164cb',
    'relationship_name' => 'bhea_orders_bhea_payments_1',
    'lhs_module' => 'Bhea_Orders',
    'lhs_table' => 'bhea_orders',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Payments',
    'rhs_table' => 'bhea_payments',
    'rhs_key' => 'id',
    'join_table' => 'bhea_orders_bhea_payments_1_c',
    'join_key_lhs' => 'bhea_orders_bhea_payments_1bhea_orders_ida',
    'join_key_rhs' => 'bhea_orders_bhea_payments_1bhea_payments_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_orders',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_bhea_orders_1' => 
  array (
    'id' => '5f09ac9e-0bec-de0d-1059-52b907abebf5',
    'relationship_name' => 'accounts_bhea_orders_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Orders',
    'rhs_table' => 'bhea_orders',
    'rhs_key' => 'id',
    'join_table' => 'accounts_bhea_orders_1_c',
    'join_key_lhs' => 'accounts_bhea_orders_1accounts_ida',
    'join_key_rhs' => 'accounts_bhea_orders_1bhea_orders_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForAccounts',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_council_members_bhea_orders_1' => 
  array (
    'id' => '5f8023a4-f3f2-a8d3-996f-52b907fa5230',
    'relationship_name' => 'bhea_council_members_bhea_orders_1',
    'lhs_module' => 'Bhea_Council_Members',
    'lhs_table' => 'bhea_council_members',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Orders',
    'rhs_table' => 'bhea_orders',
    'rhs_key' => 'id',
    'join_table' => 'bhea_council_members_bhea_orders_1_c',
    'join_key_lhs' => 'bhea_council_members_bhea_orders_1bhea_council_members_ida',
    'join_key_rhs' => 'bhea_council_members_bhea_orders_1bhea_orders_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_council_members',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_council_memberships_bhea_orders_1' => 
  array (
    'id' => '621adc76-8403-f9f0-7be6-52b907d2a160',
    'relationship_name' => 'bhea_council_memberships_bhea_orders_1',
    'lhs_module' => 'Bhea_Council_Memberships',
    'lhs_table' => 'bhea_council_memberships',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Orders',
    'rhs_table' => 'bhea_orders',
    'rhs_key' => 'id',
    'join_table' => 'bhea_council_memberships_bhea_orders_1_c',
    'join_key_lhs' => 'bhea_counc48f0erships_ida',
    'join_key_rhs' => 'bhea_council_memberships_bhea_orders_1bhea_orders_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_council_memberships',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_memberships_bhea_orders_1' => 
  array (
    'id' => '6270f865-5f55-4f0e-fc99-52b907d5bda7',
    'relationship_name' => 'bhea_memberships_bhea_orders_1',
    'lhs_module' => 'Bhea_Memberships',
    'lhs_table' => 'bhea_memberships',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Orders',
    'rhs_table' => 'bhea_orders',
    'rhs_key' => 'id',
    'join_table' => 'bhea_memberships_bhea_orders_1_c',
    'join_key_lhs' => 'bhea_memberships_bhea_orders_1bhea_memberships_ida',
    'join_key_rhs' => 'bhea_memberships_bhea_orders_1bhea_orders_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_memberships',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_orders_bhea_invoices_1' => 
  array (
    'rhs_label' => 'Invoices',
    'lhs_label' => 'Orders',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'Bhea_Orders',
    'rhs_module' => 'Bhea_Invoices',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'bhea_orders_bhea_invoices_1',
  ),
  'bhea_orders_activities_calls' => 
  array (
    'id' => '40dd9ca0-8bd4-0036-7a82-52b907e48813',
    'relationship_name' => 'bhea_orders_activities_calls',
    'lhs_module' => 'Bhea_Orders',
    'lhs_table' => 'bhea_orders',
    'lhs_key' => 'id',
    'rhs_module' => 'Calls',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Orders',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_orders_activities_meetings' => 
  array (
    'id' => '40dd9ca0-8bd4-0036-7a82-52b907e48813',
    'relationship_name' => 'bhea_orders_activities_meetings',
    'lhs_module' => 'Bhea_Orders',
    'lhs_table' => 'bhea_orders',
    'lhs_key' => 'id',
    'rhs_module' => 'Meetings',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Orders',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_orders_activities_notes' => 
  array (
    'id' => '40dd9ca0-8bd4-0036-7a82-52b907e48813',
    'relationship_name' => 'bhea_orders_activities_notes',
    'lhs_module' => 'Bhea_Orders',
    'lhs_table' => 'bhea_orders',
    'lhs_key' => 'id',
    'rhs_module' => 'Notes',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Orders',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_orders_activities_tasks' => 
  array (
    'id' => '40dd9ca0-8bd4-0036-7a82-52b907e48813',
    'relationship_name' => 'bhea_orders_activities_tasks',
    'lhs_module' => 'Bhea_Orders',
    'lhs_table' => 'bhea_orders',
    'lhs_key' => 'id',
    'rhs_module' => 'Tasks',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Orders',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_orders_activities_emails' => 
  array (
    'id' => '40dd9ca0-8bd4-0036-7a82-52b907e48813',
    'relationship_name' => 'bhea_orders_activities_emails',
    'lhs_module' => 'Bhea_Orders',
    'lhs_table' => 'bhea_orders',
    'lhs_key' => 'id',
    'rhs_module' => 'Emails',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Orders',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
);