<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

$relationships = array (
  'bhea_sessions_modified_user' => 
  array (
    'id' => '9ababfd5-176d-8124-e18b-52bac48dbea3',
    'relationship_name' => 'bhea_sessions_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Sessions',
    'rhs_table' => 'bhea_sessions',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_sessions_created_by' => 
  array (
    'id' => '9ad699a6-6abd-6839-1ad3-52bac454cfb4',
    'relationship_name' => 'bhea_sessions_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Sessions',
    'rhs_table' => 'bhea_sessions',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_sessions_assigned_user' => 
  array (
    'id' => '9b679f04-e922-3b72-f7eb-52bac4a9ebb7',
    'relationship_name' => 'bhea_sessions_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Sessions',
    'rhs_table' => 'bhea_sessions',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_sessions_bhea_registrants_1' => 
  array (
    'id' => 'b1e9ec4f-453a-47b7-6c52-52bac43f6c65',
    'relationship_name' => 'bhea_sessions_bhea_registrants_1',
    'lhs_module' => 'Bhea_Sessions',
    'lhs_table' => 'bhea_sessions',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Registrants',
    'rhs_table' => 'bhea_registrants',
    'rhs_key' => 'id',
    'join_table' => 'bhea_sessions_bhea_registrants_1_c',
    'join_key_lhs' => 'bhea_sessions_bhea_registrants_1bhea_sessions_ida',
    'join_key_rhs' => 'bhea_sessions_bhea_registrants_1bhea_registrants_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_sessions',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_sessions_bhea_sponsor_1' => 
  array (
    'id' => 'b20644e7-ae07-fede-6c0f-52bac44c20bb',
    'relationship_name' => 'bhea_sessions_bhea_sponsor_1',
    'lhs_module' => 'Bhea_Sessions',
    'lhs_table' => 'bhea_sessions',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Sponsor',
    'rhs_table' => 'bhea_sponsor',
    'rhs_key' => 'id',
    'join_table' => 'bhea_sessions_bhea_sponsor_1_c',
    'join_key_lhs' => 'bhea_sessions_bhea_sponsor_1bhea_sessions_ida',
    'join_key_rhs' => 'bhea_sessions_bhea_sponsor_1bhea_sponsor_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'opportunities_bhea_sessions_1' => 
  array (
    'id' => 'b4f0813f-51a3-5f44-e28a-52bac4c7aa6f',
    'relationship_name' => 'opportunities_bhea_sessions_1',
    'lhs_module' => 'Opportunities',
    'lhs_table' => 'opportunities',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Sessions',
    'rhs_table' => 'bhea_sessions',
    'rhs_key' => 'id',
    'join_table' => 'opportunities_bhea_sessions_1_c',
    'join_key_lhs' => 'opportunities_bhea_sessions_1opportunities_ida',
    'join_key_rhs' => 'opportunities_bhea_sessions_1bhea_sessions_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForOpportunities',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_sessions_bhea_sponsorship_1' => 
  array (
    'id' => 'b50c6816-9bd4-be64-9160-52bac428728c',
    'relationship_name' => 'bhea_sessions_bhea_sponsorship_1',
    'lhs_module' => 'Bhea_Sessions',
    'lhs_table' => 'bhea_sessions',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Sponsorship',
    'rhs_table' => 'bhea_sponsorship',
    'rhs_key' => 'id',
    'join_table' => 'bhea_sessions_bhea_sponsorship_1_c',
    'join_key_lhs' => 'bhea_sessions_bhea_sponsorship_1bhea_sessions_ida',
    'join_key_rhs' => 'bhea_sessions_bhea_sponsorship_1bhea_sponsorship_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'ForBhea_sponsorship',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_sessions_bhea_sponsorship_types_1' => 
  array (
    'id' => 'b548aa7e-9c19-a4cc-37e7-52bac43937fe',
    'relationship_name' => 'bhea_sessions_bhea_sponsorship_types_1',
    'lhs_module' => 'Bhea_Sessions',
    'lhs_table' => 'bhea_sessions',
    'lhs_key' => 'id',
    'rhs_module' => 'bhea_Sponsorship_Types',
    'rhs_table' => 'bhea_sponsorship_types',
    'rhs_key' => 'id',
    'join_table' => 'bhea_sessions_bhea_sponsorship_types_1_c',
    'join_key_lhs' => 'bhea_sessions_bhea_sponsorship_types_1bhea_sessions_ida',
    'join_key_rhs' => 'bhea_sessions_bhea_sponsorship_types_1bhea_sponsorship_types_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_sessions',
    'lhs_subpanel' => 'ForBhea_sponsorship_types',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_sessions_bhea_contractors_1' => 
  array (
    'id' => 'b5a2fe06-8b33-3da3-3a12-52bac49a3c93',
    'relationship_name' => 'bhea_sessions_bhea_contractors_1',
    'lhs_module' => 'Bhea_Sessions',
    'lhs_table' => 'bhea_sessions',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Contractors',
    'rhs_table' => 'bhea_contractors',
    'rhs_key' => 'id',
    'join_table' => 'bhea_sessions_bhea_contractors_1_c',
    'join_key_lhs' => 'bhea_sessions_bhea_contractors_1bhea_sessions_ida',
    'join_key_rhs' => 'bhea_sessions_bhea_contractors_1bhea_contractors_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_events_bhea_sessions_1' => 
  array (
    'id' => 'b6a5f38b-5844-e578-7178-52bac4835dc0',
    'relationship_name' => 'bhea_events_bhea_sessions_1',
    'lhs_module' => 'Bhea_Events',
    'lhs_table' => 'bhea_events',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Sessions',
    'rhs_table' => 'bhea_sessions',
    'rhs_key' => 'id',
    'join_table' => 'bhea_events_bhea_sessions_1_c',
    'join_key_lhs' => 'bhea_events_bhea_sessions_1bhea_events_ida',
    'join_key_rhs' => 'bhea_events_bhea_sessions_1bhea_sessions_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_events',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'contacts_bhea_sessions_1' => 
  array (
    'id' => 'b6c566c4-841a-11ce-e9b2-52bac4a6fe2c',
    'relationship_name' => 'contacts_bhea_sessions_1',
    'lhs_module' => 'Contacts',
    'lhs_table' => 'contacts',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Sessions',
    'rhs_table' => 'bhea_sessions',
    'rhs_key' => 'id',
    'join_table' => 'contacts_bhea_sessions_1_c',
    'join_key_lhs' => 'contacts_bhea_sessions_1contacts_ida',
    'join_key_rhs' => 'contacts_bhea_sessions_1bhea_sessions_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForContacts',
    'lhs_subpanel' => 'ForBhea_sessions',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_sessions_bhea_speakers_1' => 
  array (
    'rhs_label' => 'Speakers',
    'lhs_label' => 'Sessions',
    'lhs_subpanel' => 'default',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'Bhea_Sessions',
    'rhs_module' => 'Bhea_Speakers',
    'relationship_type' => 'many-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'bhea_sessions_bhea_speakers_1',
  ),
  'bhea_sessions_activities_calls' => 
  array (
    'id' => '9af7017d-8a94-04da-5667-52bac49e628e',
    'relationship_name' => 'bhea_sessions_activities_calls',
    'lhs_module' => 'Bhea_Sessions',
    'lhs_table' => 'bhea_sessions',
    'lhs_key' => 'id',
    'rhs_module' => 'Calls',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Sessions',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_sessions_activities_meetings' => 
  array (
    'id' => '9af7017d-8a94-04da-5667-52bac49e628e',
    'relationship_name' => 'bhea_sessions_activities_meetings',
    'lhs_module' => 'Bhea_Sessions',
    'lhs_table' => 'bhea_sessions',
    'lhs_key' => 'id',
    'rhs_module' => 'Meetings',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Sessions',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_sessions_activities_notes' => 
  array (
    'id' => '9af7017d-8a94-04da-5667-52bac49e628e',
    'relationship_name' => 'bhea_sessions_activities_notes',
    'lhs_module' => 'Bhea_Sessions',
    'lhs_table' => 'bhea_sessions',
    'lhs_key' => 'id',
    'rhs_module' => 'Notes',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Sessions',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_sessions_activities_tasks' => 
  array (
    'id' => '9af7017d-8a94-04da-5667-52bac49e628e',
    'relationship_name' => 'bhea_sessions_activities_tasks',
    'lhs_module' => 'Bhea_Sessions',
    'lhs_table' => 'bhea_sessions',
    'lhs_key' => 'id',
    'rhs_module' => 'Tasks',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Sessions',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_sessions_activities_emails' => 
  array (
    'id' => '9af7017d-8a94-04da-5667-52bac49e628e',
    'relationship_name' => 'bhea_sessions_activities_emails',
    'lhs_module' => 'Bhea_Sessions',
    'lhs_table' => 'bhea_sessions',
    'lhs_key' => 'id',
    'rhs_module' => 'Emails',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Sessions',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
);