<?PHP
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN Bhea_Events
 */


class Bhea_Events_sugar extends Basic {
	var $new_schema = true;
	var $module_dir = 'Bhea_Events';
	var $object_name = 'Bhea_Events';
	var $table_name = 'bhea_events';
	var $importable = true;
		var $id;
		var $name;
		var $date_entered;
		var $date_modified;
		var $modified_user_id;
		var $modified_by_name;
		var $created_by;
		var $created_by_name;
		var $description;
		var $deleted;
		var $created_by_link;
		var $modified_user_link;
		var $activities;
		var $team_id;
		var $team_set_id;
		var $team_count;
		var $team_name;
		var $team_link;
		var $team_count_link;
		var $teams;
		var $assigned_user_id;
		var $assigned_user_name;
		var $assigned_user_link;
		var $event_type;
		var $status;
		var $knowledge_area;
		var $conference_status;
		var $seminar_status;
		var $begin_date;
		var $end_date;
		var $event_coordinator;
		var $hotel;
		var $no_of_sessions;
		var $budgeted_cost;
		var $currency_id;
		var $sponsorship_target;
		var $expected_no_of_attendees;
		var $attendee_fee_target;
		var $conference_fees;
		var $early_bird_date;
		var $cancellation_fee_date;
		var $cancellation_fee;
		var $non_profit_fee;
		var $academic_fee;
		var $government_fee;
		var $corp_member_fee;
		var $member_non_profit_fee;
		var $member_academic_fee;
		var $member_government_fee;
		var $early_bird_discount;
		var $no_of_tracks;
		
	/**
	 * This is a depreciated method, please start using __construct() as this method will be removed in a future version
     *
     * @see __construct
     * @depreciated
	 */
	function Bhea_Events_sugar(){
		self::__construct();
	}

	public function __construct(){
		parent::__construct();
	}
	
	public function bean_implements($interface){
		switch($interface){
			case 'ACL': return true;
		}
		return false;
}
		
}
?>