<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

$relationships = array (
  'bhea_finance_performance_modified_user' => 
  array (
    'id' => 'bc3baa22-b38b-5adc-68ac-52b056cd163f',
    'relationship_name' => 'bhea_finance_performance_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_finance_performance',
    'rhs_table' => 'bhea_finance_performance',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_finance_performance_created_by' => 
  array (
    'id' => 'bc6a7cd9-b546-cea3-c804-52b056409cb4',
    'relationship_name' => 'bhea_finance_performance_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_finance_performance',
    'rhs_table' => 'bhea_finance_performance',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_finance_performance_assigned_user' => 
  array (
    'id' => 'bd53cce7-1032-5870-db9d-52b05696b824',
    'relationship_name' => 'bhea_finance_performance_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_finance_performance',
    'rhs_table' => 'bhea_finance_performance',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'leads_bhea_finance_performance_1' => 
  array (
    'id' => 'ce8a5f1e-5487-f39c-109c-52b0564890cc',
    'relationship_name' => 'leads_bhea_finance_performance_1',
    'lhs_module' => 'Leads',
    'lhs_table' => 'leads',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_finance_performance',
    'rhs_table' => 'bhea_finance_performance',
    'rhs_key' => 'id',
    'join_table' => 'leads_bhea_finance_performance_1_c',
    'join_key_lhs' => 'leads_bhea_finance_performance_1leads_ida',
    'join_key_rhs' => 'leads_bhea_finance_performance_1bhea_finance_performance_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForLeads',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_bhea_finance_performance_1' => 
  array (
    'id' => 'd43fe9c2-5925-8f3e-a330-52b056a15c0e',
    'relationship_name' => 'accounts_bhea_finance_performance_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_finance_performance',
    'rhs_table' => 'bhea_finance_performance',
    'rhs_key' => 'id',
    'join_table' => 'accounts_bhea_finance_performance_1_c',
    'join_key_lhs' => 'accounts_bhea_finance_performance_1accounts_ida',
    'join_key_rhs' => 'accounts_bhea_finance_performance_1bhea_finance_performance_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForAccounts',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_finance_performance_documents_1' => 
  array (
    'rhs_label' => 'Documents',
    'lhs_label' => 'Financial Performance',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'Bhea_finance_performance',
    'rhs_module' => 'Documents',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'bhea_finance_performance_documents_1',
  ),
  'bhea_finance_performance_activities_calls' => 
  array (
    'id' => 'bc97677c-1edb-3542-3dab-52b05606b1cb',
    'relationship_name' => 'bhea_finance_performance_activities_calls',
    'lhs_module' => 'Bhea_finance_performance',
    'lhs_table' => 'bhea_finance_performance',
    'lhs_key' => 'id',
    'rhs_module' => 'Calls',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_finance_performance',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_finance_performance_activities_meetings' => 
  array (
    'id' => 'bc97677c-1edb-3542-3dab-52b05606b1cb',
    'relationship_name' => 'bhea_finance_performance_activities_meetings',
    'lhs_module' => 'Bhea_finance_performance',
    'lhs_table' => 'bhea_finance_performance',
    'lhs_key' => 'id',
    'rhs_module' => 'Meetings',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_finance_performance',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_finance_performance_activities_notes' => 
  array (
    'id' => 'bc97677c-1edb-3542-3dab-52b05606b1cb',
    'relationship_name' => 'bhea_finance_performance_activities_notes',
    'lhs_module' => 'Bhea_finance_performance',
    'lhs_table' => 'bhea_finance_performance',
    'lhs_key' => 'id',
    'rhs_module' => 'Notes',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_finance_performance',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_finance_performance_activities_tasks' => 
  array (
    'id' => 'bc97677c-1edb-3542-3dab-52b05606b1cb',
    'relationship_name' => 'bhea_finance_performance_activities_tasks',
    'lhs_module' => 'Bhea_finance_performance',
    'lhs_table' => 'bhea_finance_performance',
    'lhs_key' => 'id',
    'rhs_module' => 'Tasks',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_finance_performance',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_finance_performance_activities_emails' => 
  array (
    'id' => 'bc97677c-1edb-3542-3dab-52b05606b1cb',
    'relationship_name' => 'bhea_finance_performance_activities_emails',
    'lhs_module' => 'Bhea_finance_performance',
    'lhs_table' => 'bhea_finance_performance',
    'lhs_key' => 'id',
    'rhs_module' => 'Emails',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_finance_performance',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
);