<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

$relationships = array (
  'bhea_council_memberships_modified_user' => 
  array (
    'id' => '8becbf5d-76ef-1066-ba3d-52aa95c15033',
    'relationship_name' => 'bhea_council_memberships_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Council_Memberships',
    'rhs_table' => 'bhea_council_memberships',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_council_memberships_created_by' => 
  array (
    'id' => '8c007644-c966-e81f-7cda-52aa951554d5',
    'relationship_name' => 'bhea_council_memberships_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Council_Memberships',
    'rhs_table' => 'bhea_council_memberships',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_council_memberships_assigned_user' => 
  array (
    'id' => '8c64ec7d-dfe3-09c8-00cd-52aa951cfd79',
    'relationship_name' => 'bhea_council_memberships_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Council_Memberships',
    'rhs_table' => 'bhea_council_memberships',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_council_members_bhea_council_memberships_1' => 
  array (
    'id' => 'af5a1214-f8fc-7721-a1e5-52aa95e50177',
    'relationship_name' => 'bhea_council_members_bhea_council_memberships_1',
    'lhs_module' => 'Bhea_Council_Members',
    'lhs_table' => 'bhea_council_members',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Council_Memberships',
    'rhs_table' => 'bhea_council_memberships',
    'rhs_key' => 'id',
    'join_table' => 'bhea_council_members_bhea_council_memberships_1_c',
    'join_key_lhs' => 'bhea_counc8ee0members_ida',
    'join_key_rhs' => 'bhea_counc1877erships_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_councils_bhea_council_memberships_1' => 
  array (
    'id' => 'b16e2f09-780a-533e-f35a-52aa952fa510',
    'relationship_name' => 'bhea_councils_bhea_council_memberships_1',
    'lhs_module' => 'Bhea_Councils',
    'lhs_table' => 'bhea_councils',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Council_Memberships',
    'rhs_table' => 'bhea_council_memberships',
    'rhs_key' => 'id',
    'join_table' => 'bhea_councils_bhea_council_memberships_1_c',
    'join_key_lhs' => 'bhea_councils_bhea_council_memberships_1bhea_councils_ida',
    'join_key_rhs' => 'bhea_councdfbferships_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_councils',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_council_memberships_bhea_payments_1' => 
  array (
    'id' => 'b76b5159-b993-13e0-6b45-52aa9510e76c',
    'relationship_name' => 'bhea_council_memberships_bhea_payments_1',
    'lhs_module' => 'Bhea_Council_Memberships',
    'lhs_table' => 'bhea_council_memberships',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Payments',
    'rhs_table' => 'bhea_payments',
    'rhs_key' => 'id',
    'join_table' => 'bhea_council_memberships_bhea_payments_1_c',
    'join_key_lhs' => 'bhea_counc7982erships_ida',
    'join_key_rhs' => 'bhea_council_memberships_bhea_payments_1bhea_payments_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_council_memberships',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_bhea_council_memberships_1' => 
  array (
    'id' => 'b7b24166-1c54-d28d-4d19-52aa95776da1',
    'relationship_name' => 'accounts_bhea_council_memberships_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Council_Memberships',
    'rhs_table' => 'bhea_council_memberships',
    'rhs_key' => 'id',
    'join_table' => 'accounts_bhea_council_memberships_1_c',
    'join_key_lhs' => 'accounts_bhea_council_memberships_1accounts_ida',
    'join_key_rhs' => 'accounts_bhea_council_memberships_1bhea_council_memberships_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForAccounts',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_council_memberships_bhea_orders_1' => 
  array (
    'rhs_label' => 'Orders',
    'lhs_label' => 'Council Memberships',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'Bhea_Council_Memberships',
    'rhs_module' => 'Bhea_Orders',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'bhea_council_memberships_bhea_orders_1',
  ),
  'bhea_council_memberships_activities_calls' => 
  array (
    'id' => '8c13f543-8911-31f1-127b-52aa95488a5c',
    'relationship_name' => 'bhea_council_memberships_activities_calls',
    'lhs_module' => 'Bhea_Council_Memberships',
    'lhs_table' => 'bhea_council_memberships',
    'lhs_key' => 'id',
    'rhs_module' => 'Calls',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Council_Memberships',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_council_memberships_activities_meetings' => 
  array (
    'id' => '8c13f543-8911-31f1-127b-52aa95488a5c',
    'relationship_name' => 'bhea_council_memberships_activities_meetings',
    'lhs_module' => 'Bhea_Council_Memberships',
    'lhs_table' => 'bhea_council_memberships',
    'lhs_key' => 'id',
    'rhs_module' => 'Meetings',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Council_Memberships',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_council_memberships_activities_notes' => 
  array (
    'id' => '8c13f543-8911-31f1-127b-52aa95488a5c',
    'relationship_name' => 'bhea_council_memberships_activities_notes',
    'lhs_module' => 'Bhea_Council_Memberships',
    'lhs_table' => 'bhea_council_memberships',
    'lhs_key' => 'id',
    'rhs_module' => 'Notes',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Council_Memberships',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_council_memberships_activities_tasks' => 
  array (
    'id' => '8c13f543-8911-31f1-127b-52aa95488a5c',
    'relationship_name' => 'bhea_council_memberships_activities_tasks',
    'lhs_module' => 'Bhea_Council_Memberships',
    'lhs_table' => 'bhea_council_memberships',
    'lhs_key' => 'id',
    'rhs_module' => 'Tasks',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Council_Memberships',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_council_memberships_activities_emails' => 
  array (
    'id' => '8c13f543-8911-31f1-127b-52aa95488a5c',
    'relationship_name' => 'bhea_council_memberships_activities_emails',
    'lhs_module' => 'Bhea_Council_Memberships',
    'lhs_table' => 'bhea_council_memberships',
    'lhs_key' => 'id',
    'rhs_module' => 'Emails',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Council_Memberships',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
);