<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

$relationships = array (
  'bhea_speakers_modified_user' => 
  array (
    'id' => '6e13f1a9-a06c-0bf3-5dbc-52bba6326e38',
    'relationship_name' => 'bhea_speakers_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Speakers',
    'rhs_table' => 'bhea_speakers',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_speakers_created_by' => 
  array (
    'id' => '6e2d1778-9cdd-52c7-106a-52bba677380c',
    'relationship_name' => 'bhea_speakers_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Speakers',
    'rhs_table' => 'bhea_speakers',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_speakers_assigned_user' => 
  array (
    'id' => '6eab0b08-5964-632d-a520-52bba662593d',
    'relationship_name' => 'bhea_speakers_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Speakers',
    'rhs_table' => 'bhea_speakers',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_events_bhea_speakers_1' => 
  array (
    'id' => '8134ebff-13db-1d54-094c-52bba65c56ea',
    'relationship_name' => 'bhea_events_bhea_speakers_1',
    'lhs_module' => 'Bhea_Events',
    'lhs_table' => 'bhea_events',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Speakers',
    'rhs_table' => 'bhea_speakers',
    'rhs_key' => 'id',
    'join_table' => 'bhea_events_bhea_speakers_1_c',
    'join_key_lhs' => 'bhea_events_bhea_speakers_1bhea_events_ida',
    'join_key_rhs' => 'bhea_events_bhea_speakers_1bhea_speakers_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_events',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'opportunities_bhea_speakers_1' => 
  array (
    'id' => '832b6041-6ff7-e6c0-4b3d-52bba667a787',
    'relationship_name' => 'opportunities_bhea_speakers_1',
    'lhs_module' => 'Opportunities',
    'lhs_table' => 'opportunities',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Speakers',
    'rhs_table' => 'bhea_speakers',
    'rhs_key' => 'id',
    'join_table' => 'opportunities_bhea_speakers_1_c',
    'join_key_lhs' => 'opportunities_bhea_speakers_1opportunities_ida',
    'join_key_rhs' => 'opportunities_bhea_speakers_1bhea_speakers_idb',
    'relationship_type' => 'one-to-one',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_speakers_bhea_sessions_1' => 
  array (
    'rhs_label' => 'Sessions',
    'lhs_label' => 'Speakers',
    'lhs_subpanel' => 'default',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'Bhea_Speakers',
    'rhs_module' => 'Bhea_Sessions',
    'relationship_type' => 'many-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'bhea_speakers_bhea_sessions_1',
  ),
  'bhea_speakers_activities_calls' => 
  array (
    'id' => '6e45c0a4-de38-74d1-96cd-52bba6376f4a',
    'relationship_name' => 'bhea_speakers_activities_calls',
    'lhs_module' => 'Bhea_Speakers',
    'lhs_table' => 'bhea_speakers',
    'lhs_key' => 'id',
    'rhs_module' => 'Calls',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Speakers',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_speakers_activities_meetings' => 
  array (
    'id' => '6e45c0a4-de38-74d1-96cd-52bba6376f4a',
    'relationship_name' => 'bhea_speakers_activities_meetings',
    'lhs_module' => 'Bhea_Speakers',
    'lhs_table' => 'bhea_speakers',
    'lhs_key' => 'id',
    'rhs_module' => 'Meetings',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Speakers',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_speakers_activities_notes' => 
  array (
    'id' => '6e45c0a4-de38-74d1-96cd-52bba6376f4a',
    'relationship_name' => 'bhea_speakers_activities_notes',
    'lhs_module' => 'Bhea_Speakers',
    'lhs_table' => 'bhea_speakers',
    'lhs_key' => 'id',
    'rhs_module' => 'Notes',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Speakers',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_speakers_activities_tasks' => 
  array (
    'id' => '6e45c0a4-de38-74d1-96cd-52bba6376f4a',
    'relationship_name' => 'bhea_speakers_activities_tasks',
    'lhs_module' => 'Bhea_Speakers',
    'lhs_table' => 'bhea_speakers',
    'lhs_key' => 'id',
    'rhs_module' => 'Tasks',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Speakers',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_speakers_activities_emails' => 
  array (
    'id' => '6e45c0a4-de38-74d1-96cd-52bba6376f4a',
    'relationship_name' => 'bhea_speakers_activities_emails',
    'lhs_module' => 'Bhea_Speakers',
    'lhs_table' => 'bhea_speakers',
    'lhs_key' => 'id',
    'rhs_module' => 'Emails',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Speakers',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
);