<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

$relationships = array (
  'bhea_events_modified_user' => 
  array (
    'id' => '81a349c6-5651-85f8-5d61-52b1ad3c6628',
    'relationship_name' => 'bhea_events_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Events',
    'rhs_table' => 'bhea_events',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_events_created_by' => 
  array (
    'id' => '81bcae47-ffad-a87f-53fd-52b1ada6b39f',
    'relationship_name' => 'bhea_events_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Events',
    'rhs_table' => 'bhea_events',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_events_assigned_user' => 
  array (
    'id' => '823a8eac-836d-201a-a1a8-52b1ad821836',
    'relationship_name' => 'bhea_events_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Events',
    'rhs_table' => 'bhea_events',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_events_bhea_speakers_1' => 
  array (
    'id' => '93005781-2fb9-0496-22a1-52b1ad585ca5',
    'relationship_name' => 'bhea_events_bhea_speakers_1',
    'lhs_module' => 'Bhea_Events',
    'lhs_table' => 'bhea_events',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Speakers',
    'rhs_table' => 'bhea_speakers',
    'rhs_key' => 'id',
    'join_table' => 'bhea_events_bhea_speakers_1_c',
    'join_key_lhs' => 'bhea_events_bhea_speakers_1bhea_events_ida',
    'join_key_rhs' => 'bhea_events_bhea_speakers_1bhea_speakers_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_events',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_contractors_bhea_events_1' => 
  array (
    'id' => '9373d105-5e3f-4727-a17b-52b1adbaea89',
    'relationship_name' => 'bhea_contractors_bhea_events_1',
    'lhs_module' => 'Bhea_Contractors',
    'lhs_table' => 'bhea_contractors',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Events',
    'rhs_table' => 'bhea_events',
    'rhs_key' => 'id',
    'join_table' => 'bhea_contractors_bhea_events_1_c',
    'join_key_lhs' => 'bhea_contractors_bhea_events_1bhea_contractors_ida',
    'join_key_rhs' => 'bhea_contractors_bhea_events_1bhea_events_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_contractors',
    'lhs_subpanel' => 'ForBhea_events',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_events_bhea_sponsor_1' => 
  array (
    'id' => '93adbaea-dd16-293e-b8c6-52b1ada964fb',
    'relationship_name' => 'bhea_events_bhea_sponsor_1',
    'lhs_module' => 'Bhea_Events',
    'lhs_table' => 'bhea_events',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Sponsor',
    'rhs_table' => 'bhea_sponsor',
    'rhs_key' => 'id',
    'join_table' => 'bhea_events_bhea_sponsor_1_c',
    'join_key_lhs' => 'bhea_events_bhea_sponsor_1bhea_events_ida',
    'join_key_rhs' => 'bhea_events_bhea_sponsor_1bhea_sponsor_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_events',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_events_bhea_events_1' => 
  array (
    'id' => '93e74ad5-be2b-1d6b-8b06-52b1add396f7',
    'relationship_name' => 'bhea_events_bhea_events_1',
    'lhs_module' => 'Bhea_Events',
    'lhs_table' => 'bhea_events',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Events',
    'rhs_table' => 'bhea_events',
    'rhs_key' => 'id',
    'join_table' => 'bhea_events_bhea_events_1_c',
    'join_key_lhs' => 'bhea_events_bhea_events_1bhea_events_ida',
    'join_key_rhs' => 'bhea_events_bhea_events_1bhea_events_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_events',
    'lhs_subpanel' => 'ForBhea_events',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_events_opportunities_1' => 
  array (
    'id' => '949360d4-30a9-c076-4ee2-52b1adf62651',
    'relationship_name' => 'bhea_events_opportunities_1',
    'lhs_module' => 'Bhea_Events',
    'lhs_table' => 'bhea_events',
    'lhs_key' => 'id',
    'rhs_module' => 'Opportunities',
    'rhs_table' => 'opportunities',
    'rhs_key' => 'id',
    'join_table' => 'bhea_events_opportunities_1_c',
    'join_key_lhs' => 'bhea_events_opportunities_1bhea_events_ida',
    'join_key_rhs' => 'bhea_events_opportunities_1opportunities_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_events',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_hotels_bhea_events_1' => 
  array (
    'id' => '94ec43a0-5ec6-18a3-9143-52b1adb60f2d',
    'relationship_name' => 'bhea_hotels_bhea_events_1',
    'lhs_module' => 'Bhea_Hotels',
    'lhs_table' => 'bhea_hotels',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Events',
    'rhs_table' => 'bhea_events',
    'rhs_key' => 'id',
    'join_table' => 'bhea_hotels_bhea_events_1_c',
    'join_key_lhs' => 'bhea_hotels_bhea_events_1bhea_hotels_ida',
    'join_key_rhs' => 'bhea_hotels_bhea_events_1bhea_events_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_hotels',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_events_campaigns_1' => 
  array (
    'id' => '95090429-0999-ca88-98e6-52b1add0d5f2',
    'relationship_name' => 'bhea_events_campaigns_1',
    'lhs_module' => 'Bhea_Events',
    'lhs_table' => 'bhea_events',
    'lhs_key' => 'id',
    'rhs_module' => 'Campaigns',
    'rhs_table' => 'campaigns',
    'rhs_key' => 'id',
    'join_table' => 'bhea_events_campaigns_1_c',
    'join_key_lhs' => 'bhea_events_campaigns_1bhea_events_ida',
    'join_key_rhs' => 'bhea_events_campaigns_1campaigns_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_events',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_events_bhea_sponsorship_1' => 
  array (
    'id' => '955f1992-c299-5edb-00fe-52b1ad18bde7',
    'relationship_name' => 'bhea_events_bhea_sponsorship_1',
    'lhs_module' => 'Bhea_Events',
    'lhs_table' => 'bhea_events',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Sponsorship',
    'rhs_table' => 'bhea_sponsorship',
    'rhs_key' => 'id',
    'join_table' => 'bhea_events_bhea_sponsorship_1_c',
    'join_key_lhs' => 'bhea_events_bhea_sponsorship_1bhea_events_ida',
    'join_key_rhs' => 'bhea_events_bhea_sponsorship_1bhea_sponsorship_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_events',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_events_bhea_registrants_1' => 
  array (
    'id' => '9661fea1-558a-e61f-d6f9-52b1ade4c8cf',
    'relationship_name' => 'bhea_events_bhea_registrants_1',
    'lhs_module' => 'Bhea_Events',
    'lhs_table' => 'bhea_events',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Registrants',
    'rhs_table' => 'bhea_registrants',
    'rhs_key' => 'id',
    'join_table' => 'bhea_events_bhea_registrants_1_c',
    'join_key_lhs' => 'bhea_events_bhea_registrants_1bhea_events_ida',
    'join_key_rhs' => 'bhea_events_bhea_registrants_1bhea_registrants_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_events',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_events_bhea_event_fee_1' => 
  array (
    'id' => '972dccdb-f210-430c-7699-52b1ad2c8534',
    'relationship_name' => 'bhea_events_bhea_event_fee_1',
    'lhs_module' => 'Bhea_Events',
    'lhs_table' => 'bhea_events',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Event_Fee',
    'rhs_table' => 'bhea_event_fee',
    'rhs_key' => 'id',
    'join_table' => 'bhea_events_bhea_event_fee_1_c',
    'join_key_lhs' => 'bhea_events_bhea_event_fee_1bhea_events_ida',
    'join_key_rhs' => 'bhea_events_bhea_event_fee_1bhea_event_fee_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_events',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_events_bhea_sessions_1' => 
  array (
    'id' => '97677f07-86e6-9a29-e148-52b1ad848f20',
    'relationship_name' => 'bhea_events_bhea_sessions_1',
    'lhs_module' => 'Bhea_Events',
    'lhs_table' => 'bhea_events',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Sessions',
    'rhs_table' => 'bhea_sessions',
    'rhs_key' => 'id',
    'join_table' => 'bhea_events_bhea_sessions_1_c',
    'join_key_lhs' => 'bhea_events_bhea_sessions_1bhea_events_ida',
    'join_key_rhs' => 'bhea_events_bhea_sessions_1bhea_sessions_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_events',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'leads_bhea_events_1' => 
  array (
    'id' => '97a14fb2-3a6b-5b0c-21aa-52b1adb8cfd0',
    'relationship_name' => 'leads_bhea_events_1',
    'lhs_module' => 'Leads',
    'lhs_table' => 'leads',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Events',
    'rhs_table' => 'bhea_events',
    'rhs_key' => 'id',
    'join_table' => 'leads_bhea_events_1_c',
    'join_key_lhs' => 'leads_bhea_events_1leads_ida',
    'join_key_rhs' => 'leads_bhea_events_1bhea_events_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForLeads',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_events_bhea_sponsorship_types_1' => 
  array (
    'rhs_label' => 'Sponsorship Types',
    'lhs_label' => 'Events',
    'lhs_subpanel' => 'default',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'Bhea_Events',
    'rhs_module' => 'bhea_Sponsorship_Types',
    'relationship_type' => 'many-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'bhea_events_bhea_sponsorship_types_1',
  ),
  'bhea_events_activities_calls' => 
  array (
    'id' => '81d5d02c-b0d3-750b-ff06-52b1adc18954',
    'relationship_name' => 'bhea_events_activities_calls',
    'lhs_module' => 'Bhea_Events',
    'lhs_table' => 'bhea_events',
    'lhs_key' => 'id',
    'rhs_module' => 'Calls',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Events',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_events_activities_meetings' => 
  array (
    'id' => '81d5d02c-b0d3-750b-ff06-52b1adc18954',
    'relationship_name' => 'bhea_events_activities_meetings',
    'lhs_module' => 'Bhea_Events',
    'lhs_table' => 'bhea_events',
    'lhs_key' => 'id',
    'rhs_module' => 'Meetings',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Events',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_events_activities_notes' => 
  array (
    'id' => '81d5d02c-b0d3-750b-ff06-52b1adc18954',
    'relationship_name' => 'bhea_events_activities_notes',
    'lhs_module' => 'Bhea_Events',
    'lhs_table' => 'bhea_events',
    'lhs_key' => 'id',
    'rhs_module' => 'Notes',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Events',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_events_activities_tasks' => 
  array (
    'id' => '81d5d02c-b0d3-750b-ff06-52b1adc18954',
    'relationship_name' => 'bhea_events_activities_tasks',
    'lhs_module' => 'Bhea_Events',
    'lhs_table' => 'bhea_events',
    'lhs_key' => 'id',
    'rhs_module' => 'Tasks',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Events',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_events_activities_emails' => 
  array (
    'id' => '81d5d02c-b0d3-750b-ff06-52b1adc18954',
    'relationship_name' => 'bhea_events_activities_emails',
    'lhs_module' => 'Bhea_Events',
    'lhs_table' => 'bhea_events',
    'lhs_key' => 'id',
    'rhs_module' => 'Emails',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Events',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
);