<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

$relationships = array (
  'bhea_contractors_modified_user' => 
  array (
    'id' => '691cdb17-6889-36df-1a37-52a5c1ac6d19',
    'relationship_name' => 'bhea_contractors_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Contractors',
    'rhs_table' => 'bhea_contractors',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_contractors_created_by' => 
  array (
    'id' => '693d24ac-34c8-5ef5-3307-52a5c18d9116',
    'relationship_name' => 'bhea_contractors_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Contractors',
    'rhs_table' => 'bhea_contractors',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_contractors_assigned_user' => 
  array (
    'id' => '69de25d9-db48-ced7-1aa4-52a5c14bebde',
    'relationship_name' => 'bhea_contractors_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Contractors',
    'rhs_table' => 'bhea_contractors',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_contractors_bhea_events_1' => 
  array (
    'id' => '8819ad51-92ea-725b-aa0d-52a5c116de8e',
    'relationship_name' => 'bhea_contractors_bhea_events_1',
    'lhs_module' => 'Bhea_Contractors',
    'lhs_table' => 'bhea_contractors',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Events',
    'rhs_table' => 'bhea_events',
    'rhs_key' => 'id',
    'join_table' => 'bhea_contractors_bhea_events_1_c',
    'join_key_lhs' => 'bhea_contractors_bhea_events_1bhea_contractors_ida',
    'join_key_rhs' => 'bhea_contractors_bhea_events_1bhea_events_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_contractors',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_contractors_bhea_sessions_1' => 
  array (
    'id' => '8abfa35b-086d-9f60-8d79-52a5c1f2c203',
    'relationship_name' => 'bhea_contractors_bhea_sessions_1',
    'lhs_module' => 'Bhea_Contractors',
    'lhs_table' => 'bhea_contractors',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Sessions',
    'rhs_table' => 'bhea_sessions',
    'rhs_key' => 'id',
    'join_table' => 'bhea_contractors_bhea_sessions_1_c',
    'join_key_lhs' => 'bhea_contractors_bhea_sessions_1bhea_contractors_ida',
    'join_key_rhs' => 'bhea_contractors_bhea_sessions_1bhea_sessions_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_contractors',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_contractors_contracts_1' => 
  array (
    'rhs_label' => 'Contracts',
    'lhs_label' => 'Contractors',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'Bhea_Contractors',
    'rhs_module' => 'Contracts',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'bhea_contractors_contracts_1',
  ),
  'bhea_contractors_activities_calls' => 
  array (
    'id' => '695d8471-047c-3f54-805f-52a5c1400685',
    'relationship_name' => 'bhea_contractors_activities_calls',
    'lhs_module' => 'Bhea_Contractors',
    'lhs_table' => 'bhea_contractors',
    'lhs_key' => 'id',
    'rhs_module' => 'Calls',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Contractors',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_contractors_activities_meetings' => 
  array (
    'id' => '695d8471-047c-3f54-805f-52a5c1400685',
    'relationship_name' => 'bhea_contractors_activities_meetings',
    'lhs_module' => 'Bhea_Contractors',
    'lhs_table' => 'bhea_contractors',
    'lhs_key' => 'id',
    'rhs_module' => 'Meetings',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Contractors',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_contractors_activities_notes' => 
  array (
    'id' => '695d8471-047c-3f54-805f-52a5c1400685',
    'relationship_name' => 'bhea_contractors_activities_notes',
    'lhs_module' => 'Bhea_Contractors',
    'lhs_table' => 'bhea_contractors',
    'lhs_key' => 'id',
    'rhs_module' => 'Notes',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Contractors',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_contractors_activities_tasks' => 
  array (
    'id' => '695d8471-047c-3f54-805f-52a5c1400685',
    'relationship_name' => 'bhea_contractors_activities_tasks',
    'lhs_module' => 'Bhea_Contractors',
    'lhs_table' => 'bhea_contractors',
    'lhs_key' => 'id',
    'rhs_module' => 'Tasks',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Contractors',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_contractors_activities_emails' => 
  array (
    'id' => '695d8471-047c-3f54-805f-52a5c1400685',
    'relationship_name' => 'bhea_contractors_activities_emails',
    'lhs_module' => 'Bhea_Contractors',
    'lhs_table' => 'bhea_contractors',
    'lhs_key' => 'id',
    'rhs_module' => 'Emails',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Contractors',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
);