<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

$relationships = array (
  'bhea_memberships_modified_user' => 
  array (
    'id' => '2760ff1e-ce3a-576a-2370-52af055f5ea9',
    'relationship_name' => 'bhea_memberships_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Memberships',
    'rhs_table' => 'bhea_memberships',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_memberships_created_by' => 
  array (
    'id' => '278e8e47-6b84-5a21-4d7e-52af057d5b53',
    'relationship_name' => 'bhea_memberships_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Memberships',
    'rhs_table' => 'bhea_memberships',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_memberships_assigned_user' => 
  array (
    'id' => '287a26f7-73ea-5814-9d8c-52af059627ed',
    'relationship_name' => 'bhea_memberships_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Memberships',
    'rhs_table' => 'bhea_memberships',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_memberships_bhea_payments_1' => 
  array (
    'id' => '3a91c532-9515-f6f1-5cfb-52af055b4181',
    'relationship_name' => 'bhea_memberships_bhea_payments_1',
    'lhs_module' => 'Bhea_Memberships',
    'lhs_table' => 'bhea_memberships',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Payments',
    'rhs_table' => 'bhea_payments',
    'rhs_key' => 'id',
    'join_table' => 'bhea_memberships_bhea_payments_1_c',
    'join_key_lhs' => 'bhea_memberships_bhea_payments_1bhea_memberships_ida',
    'join_key_rhs' => 'bhea_memberships_bhea_payments_1bhea_payments_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_memberships',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_member_levels_bhea_memberships_1' => 
  array (
    'id' => '3e3465ac-9522-e450-2fae-52af05788385',
    'relationship_name' => 'bhea_member_levels_bhea_memberships_1',
    'lhs_module' => 'Bhea_member_levels',
    'lhs_table' => 'bhea_member_levels',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Memberships',
    'rhs_table' => 'bhea_memberships',
    'rhs_key' => 'id',
    'join_table' => 'bhea_member_levels_bhea_memberships_1_c',
    'join_key_lhs' => 'bhea_member_levels_bhea_memberships_1bhea_member_levels_ida',
    'join_key_rhs' => 'bhea_member_levels_bhea_memberships_1bhea_memberships_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForBhea_member_levels',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_bhea_memberships_1' => 
  array (
    'id' => '40694273-745e-1ceb-710f-52af05892ef4',
    'relationship_name' => 'accounts_bhea_memberships_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'Bhea_Memberships',
    'rhs_table' => 'bhea_memberships',
    'rhs_key' => 'id',
    'join_table' => 'accounts_bhea_memberships_1_c',
    'join_key_lhs' => 'accounts_bhea_memberships_1accounts_ida',
    'join_key_rhs' => 'accounts_bhea_memberships_1bhea_memberships_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForAccounts',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'bhea_memberships_bhea_orders_1' => 
  array (
    'rhs_label' => 'Orders',
    'lhs_label' => 'Memberships',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'Bhea_Memberships',
    'rhs_module' => 'Bhea_Orders',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'bhea_memberships_bhea_orders_1',
  ),
  'bhea_memberships_activities_calls' => 
  array (
    'id' => '27bc3c97-eb8a-48e2-e7c7-52af053932ec',
    'relationship_name' => 'bhea_memberships_activities_calls',
    'lhs_module' => 'Bhea_Memberships',
    'lhs_table' => 'bhea_memberships',
    'lhs_key' => 'id',
    'rhs_module' => 'Calls',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Memberships',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_memberships_activities_meetings' => 
  array (
    'id' => '27bc3c97-eb8a-48e2-e7c7-52af053932ec',
    'relationship_name' => 'bhea_memberships_activities_meetings',
    'lhs_module' => 'Bhea_Memberships',
    'lhs_table' => 'bhea_memberships',
    'lhs_key' => 'id',
    'rhs_module' => 'Meetings',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Memberships',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_memberships_activities_notes' => 
  array (
    'id' => '27bc3c97-eb8a-48e2-e7c7-52af053932ec',
    'relationship_name' => 'bhea_memberships_activities_notes',
    'lhs_module' => 'Bhea_Memberships',
    'lhs_table' => 'bhea_memberships',
    'lhs_key' => 'id',
    'rhs_module' => 'Notes',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Memberships',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_memberships_activities_tasks' => 
  array (
    'id' => '27bc3c97-eb8a-48e2-e7c7-52af053932ec',
    'relationship_name' => 'bhea_memberships_activities_tasks',
    'lhs_module' => 'Bhea_Memberships',
    'lhs_table' => 'bhea_memberships',
    'lhs_key' => 'id',
    'rhs_module' => 'Tasks',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Memberships',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'bhea_memberships_activities_emails' => 
  array (
    'id' => '27bc3c97-eb8a-48e2-e7c7-52af053932ec',
    'relationship_name' => 'bhea_memberships_activities_emails',
    'lhs_module' => 'Bhea_Memberships',
    'lhs_table' => 'bhea_memberships',
    'lhs_key' => 'id',
    'rhs_module' => 'Emails',
    'rhs_table' => 'activities',
    'rhs_key' => 'id',
    'join_table' => 'activities_users',
    'join_key_lhs' => 'parent_id',
    'join_key_rhs' => 'activity_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Bhea_Memberships',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => true,
    'is_custom' => false,
    'from_studio' => true,
  ),
);